### PR TITLE
Tell sshd not to lookup the client IP address via DNS as it ususally …

### PR DESCRIPTION
**Pull request by codewithpassion**
…doesn't yield a result anyway and just takes time on login

### CODE REVIEW

**Comment by BrianAdams** [comment]
What happens if a person does plug the ROV in to a router? Will be still be able to ssh in to the DHCP assigned IP?

**Comment by codewithpassion** [comment]
My understanding is that this option just disables the reverse dns.

**Comment by BrianAdams** [comment]
Have you had a chance to test and get a feel of what the impact of the change is yet?

**Comment by codewithpassion** [comment]
I have had it running on my ROV without a problem.
I don't have a possibility to hock up an ROV to a router at the moment.

On 26 May 2015 at 12:55, badevguru <notifications@github.com> wrote:

> Have you had a chance to test and get a feel of what the impact of the
> change is yet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenROV/openrov-image/pull/93#issuecomment-105369917>.
>



-- 
*"Code with Passion!"*
Twitter: @codewithpassion <https://twitter.com/codewithpassion>
About: http://about.me/dominikfretz

**Comment by BrianAdams** [comment]
I believe on the latest dev image this is mute as it uses systemd to manage the dependencies

**Pull request closed without merging**
